import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { prisma } from "../db.js";
import crypto from "node:crypto";
import { ProviderType } from "@prisma/client";
import { maybeDecryptSecret } from "../utils/secretCrypto.js";

const Query = z.object({
  token: z.string().min(10)
});

function escapeXml(v: string) {
  return v.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

function base64UrlToBuffer(s: string) {
  const pad = s.length % 4 === 0 ? "" : "=".repeat(4 - (s.length % 4));
  return Buffer.from(s.replace(/-/g, "+").replace(/_/g, "/") + pad, "base64");
}

function getClientIp(req: any) {
  const xf = String(req.headers["x-forwarded-for"] ?? "").split(",")[0]?.trim();
  return xf || String(req.ip ?? req.socket?.remoteAddress ?? "unknown");
}

function isRateLimited(args: { key: string; max: number; windowMs: number }) {
  const now = Date.now();
  const entry = (globalThis as any).__ttsRl?.get(args.key) as { count: number; resetAt: number } | undefined;
  const map: Map<string, { count: number; resetAt: number }> = (globalThis as any).__ttsRl ?? new Map();
  (globalThis as any).__ttsRl = map;

  if (!entry || entry.resetAt <= now) {
    map.set(args.key, { count: 1, resetAt: now + args.windowMs });
    return false;
  }
  if (entry.count >= args.max) return true;
  entry.count += 1;
  map.set(args.key, entry);
  return false;
}

async function elevenLabsTts(args: {
  apiKey: string;
  voiceId: string;
  text: string;
  modelId?: string;
}): Promise<Uint8Array> {
  const res = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(args.voiceId)}`, {
    method: "POST",
    headers: {
      "xi-api-key": args.apiKey,
      "content-type": "application/json",
      accept: "audio/mpeg"
    },
    body: JSON.stringify({
      text: args.text,
      model_id: args.modelId ?? "eleven_multilingual_v2",
      voice_settings: {
        stability: 0.4,
        similarity_boost: 0.8,
        style: 0.2,
        use_speaker_boost: true
      }
    })
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`ElevenLabs TTS failed: ${res.status} ${escapeXml(text).slice(0, 500)}`);
  }

  const ab = await res.arrayBuffer();
  return new Uint8Array(ab);
}

export const telephonyTtsRoutes: FastifyPluginAsync = async (app) => {
  app.get("/telephony/tts", async (req, reply) => {
    const query = Query.parse(req.query);
    const secret = app.config.TELEPHONY_ANSWER_TOKEN_SECRET;
    if (!secret) return reply.notFound();

    const ip = getClientIp(req);
    if (isRateLimited({ key: `tts:${ip}`, max: 30, windowMs: 60_000 })) {
      return reply.code(429).send("Rate limited");
    }

    const [payloadB64, sigB64] = query.token.split(".");
    if (!payloadB64 || !sigB64) return reply.notFound();
    const expected = crypto.createHmac("sha256", secret).update(payloadB64).digest();
    const got = base64UrlToBuffer(sigB64);
    if (expected.length !== got.length || !crypto.timingSafeEqual(expected, got)) return reply.notFound();

    let callId = "";
    let exp = 0;
    try {
      const payload = JSON.parse(base64UrlToBuffer(payloadB64).toString("utf8")) as any;
      callId = String(payload?.callId ?? "");
      exp = Number(payload?.exp ?? 0);
    } catch {
      return reply.notFound();
    }
    if (!callId || !Number.isFinite(exp) || exp < Math.floor(Date.now() / 1000)) return reply.notFound();

    const call = await prisma.call.findUnique({ where: { id: callId } });
    if (!call || call.deletedAt) return reply.notFound();

    const cfg = await prisma.providerConfig.findFirst({
      where: { businessId: call.businessId, type: ProviderType.VOICE_ELEVENLABS, isActive: true, deletedAt: null }
    });
    const cfgJson = (cfg?.config ?? {}) as any;
    const apiKeyRaw = (cfgJson.apiKey ?? app.config.ELEVENLABS_API_KEY) as unknown;
    const apiKey =
      typeof apiKeyRaw === "string" ? (maybeDecryptSecret(apiKeyRaw, app.config.CONFIG_ENCRYPTION_KEY) as string) : undefined;
    if (!apiKey) return reply.notFound();

    const text =
      call.locale === "ar"
        ? "هذه مكالمة اختبار من EchoVora. يتم تشغيل هذا الصوت عبر ElevenLabs."
        : "This is an EchoVora test call. This audio is generated by ElevenLabs.";

    const voiceId =
      call.locale === "ar"
        ? (cfgJson.voiceIdAr ?? app.config.ELEVENLABS_VOICE_ID_AR)
        : (cfgJson.voiceIdEn ?? app.config.ELEVENLABS_VOICE_ID_EN);
    if (!voiceId) return reply.notFound();

    const started = Date.now();
    const modelId = (cfgJson.modelId ?? app.config.ELEVENLABS_MODEL_ID) as string | undefined;
    const audio = await elevenLabsTts({ apiKey, voiceId: String(voiceId), text, modelId });
    const latencyMs = Date.now() - started;

    reply.header("cache-control", "no-store");
    reply.header("x-tts-provider", "elevenlabs");
    reply.header("x-tts-latency-ms", String(latencyMs));
    reply.type("audio/mpeg");
    return reply.send(Buffer.from(audio));
  });
};
